url: ":80"

db:
  username: "admin"
  host: "streaming_service_db"
  port: "5432"
  dbname: "db"
  sslmode: "disable"

redis:
  host: "streaming_service_redis"
  port: "6379"
  db: "1"

jwt:
  key: "p2p-streaming-service-secret-jwt-golang-53237770120202024"
  issuer: "p2p-streaming-service-api"
  audience: "clients"